<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "bonificacion_alumno".
 *
 * @property integer $id
 * @property integer $id_bonificacion
 * @property integer $id_alumno
 *
 * @property \app\models\Alumno $alumno
 * @property \app\models\CategoriaBonificacion $bonificacion
 * @property string $aliasModel
 */
abstract class BonificacionAlumno extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'bonificacion_alumno';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_bonificacion', 'id_alumno'], 'required'],
            [['id_bonificacion', 'id_alumno'], 'integer'],
            [['id_alumno'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Alumno::className(), 'targetAttribute' => ['id_alumno' => 'id']],
            [['id_bonificacion'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\CategoriaBonificacion::className(), 'targetAttribute' => ['id_bonificacion' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_bonificacion' => 'Id Bonificacion',
            'id_alumno' => 'Id Alumno',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAlumno()
    {
        return $this->hasOne(\app\models\Alumno::className(), ['id' => 'id_alumno']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBonificacion()
    {
        return $this->hasOne(\app\models\CategoriaBonificacion::className(), ['id' => 'id_bonificacion']);
    }




}
