<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "bonificacion_servicio_alumno".
 *
 * @property integer $id
 * @property integer $id_bonificacion
 * @property integer $id_servicioalumno
 *
 * @property \app\models\CategoriaBonificacion $idBonificacion
 * @property \app\models\ServicioAlumno $idServicioalumno
 * @property string $aliasModel
 */
abstract class BonificacionServicioAlumno extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'bonificacion_servicio_alumno';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_bonificacion', 'id_servicioalumno'], 'required'],
            [['id_bonificacion', 'id_servicioalumno'], 'integer'],
            [['id_bonificacion'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\CategoriaBonificacion::className(), 'targetAttribute' => ['id_bonificacion' => 'id']],
            [['id_servicioalumno'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\ServicioAlumno::className(), 'targetAttribute' => ['id_servicioalumno' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_bonificacion' => 'Id Bonificacion',
            'id_servicioalumno' => 'Id Servicioalumno',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdBonificacion()
    {
        return $this->hasOne(\app\models\CategoriaBonificacion::className(), ['id' => 'id_bonificacion']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdServicioalumno()
    {
        return $this->hasOne(\app\models\ServicioAlumno::className(), ['id' => 'id_servicioalumno']);
    }




}
