<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "categoria_bonificacion".
 *
 * @property integer $id
 * @property string $descripcion
 * @property string $valor
 * @property string $tipobonificacion
 * @property boolean $activa
 *
 * @property \app\models\BonificacionAlumno[] $bonificacionAlumnos
 * @property \app\models\BonificacionServicioAlumno[] $bonificacionServicioAlumnos
 * @property string $aliasModel
 */
abstract class CategoriaBonificacion extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'categoria_bonificacion';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['descripcion', 'valor'], 'required'],
            [['valor'], 'number'],
            [['activa'], 'boolean'],
            [['descripcion', 'tipobonificacion'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'descripcion' => 'Descripcion',
            'valor' => 'Valor',
            'tipobonificacion' => 'Tipobonificacion',
            'activa' => 'Activa',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBonificacionAlumnos()
    {
        return $this->hasMany(\app\models\BonificacionAlumno::className(), ['id_bonificacion' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBonificacionServicioAlumnos()
    {
        return $this->hasMany(\app\models\BonificacionServicioAlumno::className(), ['id_bonificacion' => 'id']);
    }




}
