<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "cuentas".
 *
 * @property integer $id
 * @property string $nombre
 * @property string $fecha_apertura
 * @property string $saldo_inicial
 * @property string $saldo_actual
 *
 * @property \app\models\MovimientoCuenta[] $movimientoCuentas
 * @property string $aliasModel
 */
abstract class Cuentas extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'cuentas';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombre', 'fecha_apertura', 'saldo_inicial', 'saldo_actual'], 'required'],
            [['fecha_apertura'], 'safe'],
            [['saldo_inicial', 'saldo_actual'], 'number'],
            [['nombre'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'fecha_apertura' => 'Fecha Apertura',
            'saldo_inicial' => 'Saldo Inicial',
            'saldo_actual' => 'Saldo Actual',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMovimientoCuentas()
    {
        return $this->hasMany(\app\models\MovimientoCuenta::className(), ['id_cuenta' => 'id']);
    }




}
