<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "division_escolar".
 *
 * @property integer $id
 * @property string $nombre
 * @property integer $id_establecimiento
 *
 * @property \app\models\Alumno[] $alumnos
 * @property \app\models\Establecimiento $establecimiento
 * @property \app\models\ServicioEstablecimiento[] $servicioEstablecimientos
 * @property string $aliasModel
 */
abstract class DivisionEscolar extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'division_escolar';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombre', 'id_establecimiento'], 'required'],
            [['id_establecimiento'], 'integer'],
            [['nombre'], 'string', 'max' => 50],
            [['id_establecimiento'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Establecimiento::className(), 'targetAttribute' => ['id_establecimiento' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'id_establecimiento' => 'Id Establecimiento',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getAlumnos()
    {
        return $this->hasMany(\app\models\Alumno::className(), ['id_divisionescolar' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEstablecimiento()
    {
        return $this->hasOne(\app\models\Establecimiento::className(), ['id' => 'id_establecimiento']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getServicioEstablecimientos()
    {
        return $this->hasMany(\app\models\ServicioEstablecimiento::className(), ['id_divisionescolar' => 'id']);
    }




}
