<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "egresos_fondofijo".
 *
 * @property integer $id
 * @property integer $id_fondofijo
 * @property integer $id_clasificacionegreso
 * @property string $fecha_compra
 * @property string $proovedor
 * @property string $descripcion
 * @property string $importe
 * @property string $nro_factura
 * @property string $nro_rendicion
 * @property boolean $bien_uso
 * @property boolean $rendido
 *
 * @property \app\models\FondoFijo $fondofijo
 * @property string $aliasModel
 */
abstract class EgresoFondoFijo extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'egresos_fondofijo';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_fondofijo', 'id_clasificacionegreso', 'fecha_compra', 'proovedor', 'descripcion', 'importe'], 'required'],
            [['id_fondofijo', 'id_clasificacionegreso'], 'integer'],
            [['fecha_compra'], 'safe'],
            [['importe', 'nro_factura', 'nro_rendicion'], 'number'],
            [['bien_uso', 'rendido'], 'boolean'],
            [['proovedor', 'descripcion'], 'string', 'max' => 255],
            [['id_fondofijo'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\FondoFijo::className(), 'targetAttribute' => ['id_fondofijo' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_fondofijo' => 'Id Fondofijo',
            'id_clasificacionegreso' => 'Id Clasificacionegreso',
            'fecha_compra' => 'Fecha Compra',
            'proovedor' => 'Proovedor',
            'descripcion' => 'Descripcion',
            'importe' => 'Importe',
            'nro_factura' => 'Nro Factura',
            'nro_rendicion' => 'Nro Rendicion',
            'bien_uso' => 'Bien Uso',
            'rendido' => 'Rendido',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFondofijo()
    {
        return $this->hasOne(\app\models\FondoFijo::className(), ['id' => 'id_fondofijo']);
    }




}
