<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "fondo_fijo".
 *
 * @property integer $id
 * @property integer $id_establecimiento
 * @property string $monto_actual
 * @property string $alerta_tope_maximo
 * @property string $tope_compra
 *
 * @property \app\models\EgresosFondofijo[] $egresosFondofijos
 * @property \app\models\Establecimiento $establecimiento
 * @property string $aliasModel
 */
abstract class FondoFijo extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'fondo_fijo';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_establecimiento', 'monto_actual', 'alerta_tope_maximo', 'tope_compra'], 'required'],
            [['id_establecimiento'], 'integer'],
            [['monto_actual', 'alerta_tope_maximo', 'tope_compra'], 'number'],
            [['id_establecimiento'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Establecimiento::className(), 'targetAttribute' => ['id_establecimiento' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_establecimiento' => 'Id Establecimiento',
            'monto_actual' => 'Monto Actual',
            'alerta_tope_maximo' => 'Alerta Tope Maximo',
            'tope_compra' => 'Tope Compra',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEgresosFondofijos()
    {
        return $this->hasMany(\app\models\EgresosFondofijo::className(), ['id_fondofijo' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getEstablecimiento()
    {
        return $this->hasOne(\app\models\Establecimiento::className(), ['id' => 'id_establecimiento']);
    }




}
