<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "forma_pago".
 *
 * @property integer $id
 * @property string $nombre
 * @property string $siglas
 *
 * @property \app\models\GrupoFamiliar[] $grupoFamiliars
 * @property \app\models\MovimientoCuenta[] $movimientoCuentas
 * @property \app\models\Tiket[] $tikets
 * @property string $aliasModel
 */
abstract class FormaPago extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'forma_pago';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['nombre', 'siglas'], 'required'],
            [['nombre'], 'string', 'max' => 100],
            [['siglas'], 'string', 'max' => 30]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'nombre' => 'Nombre',
            'siglas' => 'Siglas',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGrupoFamiliars()
    {
        return $this->hasMany(\app\models\GrupoFamiliar::className(), ['id_pago_asociado' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getMovimientoCuentas()
    {
        return $this->hasMany(\app\models\MovimientoCuenta::className(), ['id_tipopago' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTikets()
    {
        return $this->hasMany(\app\models\Tiket::className(), ['id_formapago' => 'id']);
    }




}
