<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "movimiento_cuenta".
 *
 * @property integer $id
 * @property integer $id_cuenta
 * @property string $tipo_movimiento
 * @property string $detalle_movimiento
 * @property string $importe
 * @property string $fecha_realizacion
 * @property string $comentario
 * @property integer $id_tipopago
 * @property integer $id_hijo
 *
 * @property \app\models\Cuentas $idCuenta
 * @property \app\models\FormaPago $idTipopago
 * @property string $aliasModel
 */
abstract class MovimientoCuenta extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'movimiento_cuenta';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_cuenta', 'tipo_movimiento', 'detalle_movimiento', 'importe', 'fecha_realizacion'], 'required'],
            [['id_cuenta', 'id_tipopago', 'id_hijo'], 'integer'],
            [['importe'], 'number'],
            [['fecha_realizacion'], 'safe'],
            [['tipo_movimiento', 'detalle_movimiento', 'comentario'], 'string', 'max' => 255],
            [['id_cuenta'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Cuentas::className(), 'targetAttribute' => ['id_cuenta' => 'id']],
            [['id_tipopago'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\FormaPago::className(), 'targetAttribute' => ['id_tipopago' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_cuenta' => 'Id Cuenta',
            'tipo_movimiento' => 'Tipo Movimiento',
            'detalle_movimiento' => 'Detalle Movimiento',
            'importe' => 'Importe',
            'fecha_realizacion' => 'Fecha Realizacion',
            'comentario' => 'Comentario',
            'id_tipopago' => 'Id Tipopago',
            'id_hijo' => 'Id Hijo',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdCuenta()
    {
        return $this->hasOne(\app\models\Cuentas::className(), ['id' => 'id_cuenta']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getIdTipopago()
    {
        return $this->hasOne(\app\models\FormaPago::className(), ['id' => 'id_tipopago']);
    }




}
