<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "servicio_convenio_pago".
 *
 * @property integer $id
 * @property integer $id_conveniopago
 * @property integer $id_servicio
 *
 * @property \app\models\ConvenioPago $conveniopago
 * @property \app\models\ServicioAlumno $servicio
 * @property string $aliasModel
 */
abstract class ServicioConvenioPago extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'servicio_convenio_pago';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['id_conveniopago', 'id_servicio'], 'required'],
            [['id_conveniopago', 'id_servicio'], 'integer'],
            [['id_conveniopago'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\ConvenioPago::className(), 'targetAttribute' => ['id_conveniopago' => 'id']],
            [['id_servicio'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\ServicioAlumno::className(), 'targetAttribute' => ['id_servicio' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'id_conveniopago' => 'Id Conveniopago',
            'id_servicio' => 'Id Servicio',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getConveniopago()
    {
        return $this->hasOne(\app\models\ConvenioPago::className(), ['id' => 'id_conveniopago']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getServicio()
    {
        return $this->hasOne(\app\models\ServicioAlumno::className(), ['id' => 'id_servicio']);
    }




}
