<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "tiket".
 *
 * @property integer $id
 * @property string $fecha_tiket
 * @property integer $id_formapago
 * @property string $importe
 * @property string $detalles
 * @property integer $id_cliente
 *
 * @property \app\models\ServicioTiket[] $servicioTikets
 * @property \app\models\GrupoFamiliar $cliente
 * @property \app\models\FormaPago $formapago
 * @property string $aliasModel
 */
abstract class Tiket extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'tiket';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['fecha_tiket'], 'safe'],
            [['id_formapago', 'importe', 'id_cliente'], 'required'],
            [['id_formapago', 'id_cliente'], 'integer'],
            [['importe'], 'number'],
            [['detalles'], 'string', 'max' => 255],
            [['id_cliente'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\GrupoFamiliar::className(), 'targetAttribute' => ['id_cliente' => 'id']],
            [['id_formapago'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\FormaPago::className(), 'targetAttribute' => ['id_formapago' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'fecha_tiket' => 'Fecha Tiket',
            'id_formapago' => 'Id Formapago',
            'importe' => 'Importe',
            'detalles' => 'Detalles',
            'id_cliente' => 'Id Cliente',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getServicioTikets()
    {
        return $this->hasMany(\app\models\ServicioTiket::className(), ['id_tiket' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCliente()
    {
        return $this->hasOne(\app\models\GrupoFamiliar::className(), ['id' => 'id_cliente']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getFormapago()
    {
        return $this->hasOne(\app\models\FormaPago::className(), ['id' => 'id_formapago']);
    }




}
